### PR TITLE
Histogram ticklabelprops fix

### LINKED ISSUE #183: histogram tickLabelProps
Hi, thanks making this library!

I am having an issue trying to pass tickLabelProps into a histogram XAxis.
When I do pass in a custom tickLabelProps function I get the following error:

VM538 1.chunk.js:894 Uncaught TypeError: Cannot read property 'bottom' of undefined

I believe I've tracked it down to the fix from commit 3a594deca588dd7761957f54de31177f09bed830 not being applied to the histogram axes.

I am having trouble confirming this locally since I am not familiar with installing local npm packages, but I believe simply applying the same fix as in packages/xy-chart/src/axis/XAxis.jsx should fix the issue.

Thanks

### PR DESCRIPTION
**Pull request by mfe5003**
🐛 Bug Fix
Applies the same fix from #82 for histogram axes as well.
Closes #183

### CODE REVIEW

File: packages/histogram/src/axis/YAxis.jsx [hunk 1]
```diff
@@ -53,10 +53,13 @@ export default function YAxis({
...
   const Axis = orientation === 'left' ? AxisLeft : AxisRight;
 
-  const tickLabelProps =
-    passedTickLabelProps || (tickStyles.label && tickStyles.label[orientation])
-      ? () => tickStyles.label[orientation]
-      : undefined;
+  let tickLabelProps = passedTickLabelProps;
+
+  if (!tickLabelProps) {
+    tickLabelProps = tickStyles.label && tickStyles.label[orientation] ? function () {
```
Comment (williaster) [inline packages/histogram/src/axis/YAxis.jsx]: Any reason you are not using an arrow function `() => ...`  here?
